trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Postgres
- group: Docker
- name: imageTag
  value: '$(frontEndContainer)-$(Build.BuildId)'
- name: dockerHubServiceConnection
  value: 'Docker Hub'

steps:
- task: Docker@2
  displayName: 'Build Docker image for front-end'
  inputs:
    command: 'build'
    containerRegistry: $(dockerHubServiceConnection)
    repository: '$(DockerUsername)/$(DockerRepo)'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)
    arguments: '--build-arg DB_USER=$(DB_USER) --build-arg DB_PASS=$(DB_PASS) --build-arg DB_NAME=$(DB_NAME)'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    command: 'push'
    containerRegistry: $(dockerHubServiceConnection)
    repository: '$(DockerUsername)/$(DockerRepo)'
    tags: |
      $(imageTag)
